spring:
  profiles:
    active:
      - cat
      - FR
      - dev
guru:
  username: ymlUsername
  password: ymlPassword
  jdbcurl: ymlUrl

---
spring:
  config:
    activate:
      on-profile: prod
guru:
  username: ymlProdUsername
  password: ymlProdPassword
  jdbcurl: ymlProdUrl

